
[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[functions."*"]
  external_node_modules = ["@netlify/blobs"]
[build.processing]
  skip_processing = true

